name: Test Slack Notification

on:
  workflow_dispatch:  # Trigger manually from GitHub Actions tab

jobs:
  slack-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔔 Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#36a64f'
          SLACK_TITLE: "✅ Slack Test Success"
          SLACK_MESSAGE: |
            This is a test message from GitHub Actions confirming Slack integration is working.
            Time: ${{ github.event.repository.updated_at }}
